### PR TITLE
Cleanup Examples

### LINKED ISSUE #18: Convert `Examples` to demos or vignettes
The `Examples/` directory is currently a collection of 4 R scripts which are essentially demos. This should be formalized demos; currently, a user has no good way to run these Examples anyways.

According to [Hadley](http://r-pkgs.had.co.nz/misc.html), demos are inferior to vignettes. Not only that, but demos appear to be ran from wherever a user types `demo()`, which would be a problem for the paths in the xqt scripts (which would themselves be moved to `extdata`). If it was instead the case that demos run from `RQt/demo/` in our case, we could more easily get the paths working and stick with demos for now.

According to the same link, the demos aren't even checked automatically, though I wouldn't be surprised if the CRAN maintainers checked them manually, at least for the first submission of a package.

I'll make a branch and edit things assuming demos are ran from `RQT/demo`, but again @javadch will have to test for me. If that doesn't work we either need a different way to inject paths into an xqt script, or we need to write a vignette for these long examples.

### PR DESCRIPTION
**Pull request by ClaytonJY**
This PR accomplishes the following:
- moved xqt files from `inst/Examples/processes/` into `inst/extdata/`
- updated references to those xqt files
- rebuilt documentation for functions whose examples changed due to above
- moved R scripts from `inst/Examples/R/` into `demo/`
- added an Index file for the demos (note I did _not_ give them real descriptions)

This at least partially fixes #18, though I have no idea if the demos actually work as I am unable to test them.  The demos seem to conflict in how they use pathing ("extdata" or "inst/extdata"), so I doubt they all worked before anyways. If the package is loaded, demos are ran like `demo("RQtTest2", package = "RQt")`.

### CODE REVIEW

**Comment by ClaytonJY** [comment]
Just added another commit which fixed two bad paths still using "inst". Package building removes that folder, examples in function docs are not run until after build, and demos are run from an installed package, so neither of those should ever reference `inst`.

**Comment by ClaytonJY** [comment]
Conflicts caused by #25; will hopefully fix tonight.

**Comment by ClaytonJY** [comment]
Merge conflicts addressed. @javadch, please review.

**Comment by javadch** [comment]
There are still two reference to the "Examples" folder in the doc of the getVariable function at lines 193 and 199
system.file("Examples/processes", "ex2.xqt", package="RQt"). changing them

**Comment by ClaytonJY** [comment]
Dang, can't believe I missed those.

**Comment by javadch** [comment]
@ClaytonJY did you fix it or should I do it? let me know before noon, otherwise I go ahead.

**Comment by ClaytonJY** [comment]
@javadch sorry about the delay, just pushed the fix.

**Pull request merged**
