### PR TITLE
Removed getPlot function from the R package

### PR DESCRIPTION
**Pull request by javadch**

### CODE REVIEW

**Comment by ClaytonJY** [comment]
This commit does more than just remove that function. Why? What changed in the jar file, and why are you editing unrelated documentation in this commit?

**Comment by javadch** [comment]
Sorry for that. The jar change was for a new function that will be added to
the package later. Does not affect anything. The doc change was because the
sentence was wrong.

**Comment by ClaytonJY** [comment]
What about the removal of the `rqt.getProcess` call in the function doc examples for `rqt.getVariable`?

**Comment by javadch** [comment]
It was also mistakenly there, should have been. I had added to see whether
the loadProcess function loads the script files correctly or not, but
forgot to remove it. Which then remove it by this commit.

**Comment by ClaytonJY** [comment]
Merging; in the future, it would be better to keep separate issues in separate commits/branches.

**Comment by javadch** [comment]
Yes Sir :-)

**Pull request merged**
