### PR TITLE
Simple cleanup

### LINKED ISSUE #1: Malformed DESCRIPTION file
Build check shows the DESCRIPTION file needs updating

```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
Non-standard license specification:
  What license is it under?
```

https://www.r-project.org/Licenses/

### LINKED ISSUE #2: Non-standard files/directories found at top level
```
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
Non-standard files/directories found at top level:
  ‘Examples’ ‘config’ ‘docs’
```

### LINKED ISSUE #3: Malformed NAMESPACE file
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘rJava’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

### LINKED ISSUE #5: Non-portable file name
```
* checking for portable file names ... WARNING
Found the following file with a non-portable file name:
  docs/Simplified Data Access for Scientists.pptx
```

### PR DESCRIPTION
**Pull request by ClaytonJY**
This is a pretty large PR covering what I saw as relatively easy fixes to get this package into a state which better conforms to modern best practices. This was informed by [Hadley's guide](http://r-pkgs.had.co.nz/), the [XLConnect package](https://github.com/miraisolutions/xlconnect) which also uses `rJava`, and my own experience as a package author.

I tried to write descriptive commit messages; I suggest you look over them when reviewing this PR.

This doesn't fix the big `R CMD check` issues, just some small ones:
- Fixes #5 
- Fixes #3 
- Fixes #2 
- Fixes #1 

Notes about the changes to DESCRIPTION:
- I made @javadch the maintainer, and added @ellisvalentiner and I as authors. Javad, you expressed desire to NOT be the maintainer of this wrapper package, and I may be willing to take that responsibility eventually, but it seems premature for now.
- I did not spend much time thinking about the Title and Description fields; I just wanted _something_ in them. These may require more discussion to get right.
- removed the `Date:` field as it isn't really used and remembering to update it is an annoyance. Timestamping is better handled by having explicit Releases, and eventually a NEWS file.
- I changed the version to `0.1` as it is in the earliest stages of development; I suggest we use [Semantic Versioning](http://semver.org/) as discussed by Hadley [here](http://r-pkgs.had.co.nz/description.html#version).

Notes about workflow:
- I created a `develop` branch to merge into, rather than merging directly into `master`; I recommend we only push tagged releases to master to keep it clean, particularly in these early stages, but I'm open to other workflows as well.

### CODE REVIEW

**Comment by javadch** [comment]
according to the semantic versioning scheme @ClaytonJY has shared, the version number should be three segments. The first digit shows the Major release which is the API changes. So I suggest the first version to be 1.0.0. Because starting with just two digits breaks the guideline and starting with Major version 0 makes no sense, because the first version has an API, too.

**Comment by javadch** [comment]
From the document:
A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

**Comment by javadch** [comment]
Or based on the rule 4:
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by ClaytonJY** [comment]
@javadch I agree it should be 3 numbers, that's my mistake. I agree with your last comment; let's stick with < 1.0.0 for now, until we really have this project in a stable spot. I'll make a quick commit + push to `develop` to more fully specify the version.

**Pull request merged**
