### PR TITLE
Edited some lines for length to fix overfull hboxes 

### LINKED ISSUE #12: Fix LaTeX issue in documentation
Running `R CMD check` gives the following:

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... OK
* DONE
```

This means there's some improper documentation code, almost certainly in `R/RQt.R`, as that's where all the documentation is. This needs to be tracked down, and will resolve the last Warning I see.

### PR DESCRIPTION
**Pull request by ClaytonJY**
@javadch, see the changes I made to the examples in `R/Rqt.R`; because the examples have never worked for me, I don't know if writing the scripts on multiple lines breaks anything or not. You said elsewhere that you could handle Windows newlines, `\r\n`, so as long as that handling is done in a platform-agnostic way I would expect this change to be just fine. Still worth testing before merging.

Should fix #12.

### CODE REVIEW

**Comment by ClaytonJY** [comment]
Oh hold on, let me fix this to allow auto-merging.

**Comment by ClaytonJY** [comment]
Nevermind, I'm just gonna put this right on `develop`.

**Comment by javadch** [comment]
Is the develop branch updated now? can I proceed?

**Comment by javadch** [comment]
I just did a fresh install of Miktex, No latex warning anymore and the manual PDF is created.

**Comment by ClaytonJY** [comment]
I _just_ pushed my commit, so I'm surprised you didn't have `overfull hbox` errors.

**Pull request closed without merging**
